### ISSUE TITLE
Prepare for use with mkdocs-static-i18n

### ISSUE THREAD

**Issue by joaolrc** [try0/mkdocs-toc-md#4]
First of all, thanks for making this project.. exactly what i was looking for.

What i am about to post is not really an issue but a feature request.

While using mkdocs-static-i18n plugin, one ends with a structure like (assuming pt and en as site languages):
```
├── docs
│   ├── Home
│   │   ├── index.pt.md
│   │   ├── index.en.md
│   ├── index.pt.md
│   ├── index.en.md
│   ├── mkdocs.yml
  
```

So, 2 indexes must be created. One that includes only *.en.md files for en version and another that includes *.pt.md for portuguese version home page.

I already see that you have a feature to erxclude/include filex by pattern/regex.
It would be great that we could combine that and instruct your plugin to create 2 separata index.<something>.md to create a home page per language.

Kind Regards!

**Comment by try0** [comment]
Hi @joaolrc 

Thank you for having an interest in this project.
I don't know if I can do it, but I'll try. 👍

**Comment by try0** [comment]
@joaolrc 

I have released a v0.0.6 that supports mkdocs-static-i18n.
Could you please check to see if this release satisfies your request?

1. Update plugin  to v0.0.6
1. Adds setting for mkdocs-static-i18n
```yml
      integrate_mkdocs_static_i18n: true
      languages:
        en:
          toc_page_title: Contents
          toc_page_description: Usage mkdocs-toc-md
        ja:
          toc_page_title: 目次
          toc_page_description: mkdocs-toc-mdプラグインの使い方
```
Sample [mkdocs.yml](https://github.com/try0/mkdocs-toc-md/blob/main/sample/mkdocs.yml#L27)
